import type { OperationDescriptor } from './types.ts'

export const JSON_OPERATION_CATALOG: readonly OperationDescriptor[] = [
  ['value.add', 'Add value', 'command'],
  ['header.add', 'Add nested header', 'command'],
  ['subtree.duplicate', 'Duplicate', 'command'],
  ['header.rename', 'Rename', 'command'],
  ['node.convert', 'Convert', 'command'],
  ['node.wrap', 'Wrap', 'command'],
  ['header.unwrap', 'Unwrap', 'command'],
  ['header.clear', 'Clear', 'command'],
  ['structure.move', 'Move up or down', 'operation'],
  ['structure.move-to', 'Move to container', 'operation'],
  ['structure.reverse', 'Reverse children', 'operation'],
  ['structure.flatten', 'Flatten collections', 'operation'],
  ['structure.remove-empty', 'Remove empty values', 'operation'],
  ['structure.remove', 'Remove selection', 'operation'],
  ['text.case', 'Change case', 'operation'],
  ['text.trim', 'Trim', 'operation'],
  ['text.replace', 'Find and replace', 'operation'],
  ['text.affix', 'Add prefix or suffix', 'operation'],
  ['text.parse-escaped', 'Parse escaped string', 'operation'],
  ['text.escape', 'Escape string', 'operation'],
  ['primitive.convert', 'Convert primitive', 'operation'],
  ['primitive.date-format', 'Date recognition display', 'operation'],
  ['primitive.number-format', 'Number formatting', 'operation'],
  ['primitive.generate', 'Generate value', 'operation'],
  ['primitive.toggle', 'Toggle boolean', 'operation'],
  ['primitive.adjust', 'Adjust number', 'operation'],
  ['collection.sort', 'Sort', 'operation'],
  ['collection.filter', 'Filter', 'operation'],
  ['collection.deduplicate', 'Deduplicate', 'operation'],
  ['collection.group', 'Group', 'operation'],
  ['collection.reorder', 'Reorder', 'operation'],
  ['data.merge', 'Merge', 'operation'],
  ['data.diff', 'Diff', 'operation'],
  ['data.extract', 'Extract', 'operation'],
  ['data.rename-path', 'Rename path segment', 'operation'],
].map(([id, label, implementation]) => ({
  id,
  label,
  implementation,
})) as readonly OperationDescriptor[]
